version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .

# Don't build any extra formats
formats: []
