name: "Documentation check"
on:
  - pull_request

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PennyLaneAI/sphinx-action@master
        with:
          docs-folder: "doc/"
          pre-build-command: "apt install -y graphviz gcc python3-dev git"
          build-command: "sphinx-build -b html . _build -W --keep-going"
