name: Formatting check
on:
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install black

      - uses: actions/checkout@v3

      - name: Run Black
        run: black -l 120 pennylane_quantuminspire/ --check
